
name: Data Preprocessing CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run preprocessing script
      working-directory: preprocessing
      run: |
        python automate.py

    - name: Commit and push processed data
      if: success()
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Update pre-processed data'
        file_pattern: |
          data/processed/fraud_detection_processed.csv
          data/processed/column_list_processed.csv
          models/preprocessing/preprocessor.csv
        commit_user_name: 'github-actions[bot]'
        commit_user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
